apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
        - name: log-sidecar
          image: busybox:1.28
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          command: ["sh", "-c", "while true; do echo sync logs; sleep 20; done"]
