apiVersion: v1
kind: Pod
metadata:
  name: nginx-app-tolerations
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  tolerations:
    - effect: NoExecute
      operator: Exists
